[WIP] Fix resource deallocation
Change-Id: I8e9c7964c923f1c8c709897e73ccc240c571bd76
Partial-Bug: #1611432

diff --git a/murano-ci/jenkins/jobs/macros.yaml b/murano-ci/jenkins/jobs/macros.yaml
--- a/murano-ci/jenkins/jobs/macros.yaml
+++ b/murano-ci/jenkins/jobs/macros.yaml
@@ -10,8 +10,25 @@
                 source "${WORKSPACE}/murano-ci/scripts/common.inc"
                 #-----------------
 
+                pushd "${STACK_HOME}/devstack"
+                set +o xtrace
+                echo "Importing openrc ..."
+                source openrc "${ADMIN_USERNAME}" "${ADMIN_TENANT}"
+                set -o xtrace
+                popd
+
                 source "${WORKSPACE}/murano-ci/scripts/collect_results.sh"
                 source "${WORKSPACE}/murano-ci/scripts/collect_logs.sh"
+
+                # Cleaning up resources
+                sudo pkill murano || true
+                # wait till murano processes gracefully shutdown
+                while pgrep -f murano-api || pgrep -f murano-engine ; do
+                    sleep 10
+                done
+                # cleanup stacks
+                ensure_no_heat_stacks_left
+
           onsuccess: false
           onfailure: false
           script-only-if-succeeded: false
